# Site settings

# Change these values to customize your site

title: Tech News Blog
description: The latest updates and insights in technology.
author: Prawesh Meshram
email: prmeshram358@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourgithubusername.github.io/tech-news-blog" # your GitHub Pages URL

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Social
twitter_username: yourtwitter
github_username: yourgithubusername
